#!/usr/bin/zsh

config="$(pwd)/project.conf"

. $config

# folder="build/$(echo $board_fqbn|sed 's/:/./g')"

data_folder="data"
bin_folder="build/bin"
tmp_folder="build/tmp"
firmware_file="$bin_folder/${PWD##*/}.ino.bin"
filesystem_file="filesystem.bin"

usage() {
	echo "[-c <--compile>] [-f <--filesystem>] [-e <--erase>] [-u <--upload>] [-o <--upload-ota>] [-m <--monitor>]" 1>&2
	exit 1
}

if [[ -z $1 ]]; then
	usage
fi

baud() {
	generate_banner "invalid baudrate!" 80 "-"
	echo -e "\nAvailable baudrates: 57600, 115200, 230400, 460800, 921600." 1>&2
	exit 1
}

speeds=(57600 115200 230400 460800 921600)
(($baudrate == 57600 || $baudrate == 115200 || $baudrate == 230400 || $baudrate == 460800 || $baudrate == 921600)) || baud

if [[ ! $ip =~ '\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}\b' ]]; then
	generate_banner "$ip is not a valid IP address!" 80 "-"
	exit 1
fi

if [[ ! $net_port =~ '^[0-9]+$' ]]; then
	generate_banner "$net_port is not a valid port number!" 80 "-"
	exit 1
fi

generate_banner() {
    local string="$1"
    local length="$2"
    local symbol="$3"
    local symbol_length=${#symbol}
    local text_length=${#string}
    local remaining_length=$((length - symbol_length * 2 - text_length))
    local half_remaining_length=$((remaining_length / 2))
    local banner=""
    for ((i=0; i<half_remaining_length; i++)); do
        banner+="$symbol"
    done
    banner+=" $string "
    for ((i=0; i<half_remaining_length; i++)); do
        banner+="$symbol"
    done
    local total_length=${#banner}
    local remaining_chars=$((length - total_length))
    for ((i=0; i<remaining_chars; i++)); do
        banner+="$symbol"
    done
    echo "$banner"
}

compile() {
	echo "arduino-cli compile --fqbn $board_fqbn --board-options $board_options --build-path $tmp_folder --output-dir $bin_folder"
	arduino-cli compile --fqbn $board_fqbn --board-options $board_options --build-path $tmp_folder --output-dir $bin_folder
}

flash_fs_esp8266() {
	if [[ $fs_size == "1M" ]];then
		fs_size=1024000
	elif [[ $fs_size == "2M" ]];then
		fs_size=2072576
	elif [[ $fs_size == "3M" ]];then
		fs_size=3121152
	else
		generate_banner "fs_size not specified!" 80 "-"
		exit 1
	fi
	fs_address="0x$(echo "4-${fs_size::1}"|bc)00000"
	mklittlefs -c $data_folder -p 256 -b 8192 -s $fs_size "$bin_folder/$filesystem_file"
	generate_banner "$board:$fs_address:$fs_size" 40 "+"
	echo "esptool.py -p $port -c $board -b $baudrate write_flash $fs_address \"$bin_folder/$filesystem_file\""
	esptool.py -p $port -c $board -b $baudrate write_flash $fs_address "$bin_folder/$filesystem_file"
}

flash_fs_esp32() {
	if test -f "$tmp_folder/partitions.csv"; then
		generate_banner "found partitions" 40 "+"
		fs_size=$(cat $tmp_folder/partitions.csv|rg spiffs|awk -F ',' '{print $5}')
		fs_address=$(cat build/tmp/partitions.csv|rg spiffs|awk -F ',' '{print $4}'|sed 's/\s*//g')
		mklittlefs -c $data_folder -s $fs_size "$bin_folder/$filesystem_file"
		generate_banner "$board:$fs_address:$fs_size" 40 "+"
		echo "esptool.py -p $port -c $board -b $baudrate write_flash $fs_address \"$bin_folder/$filesystem_file\""
		esptool.py -p $port -c $board -b $baudrate write_flash $fs_address "$bin_folder/$filesystem_file"
	else
		generate_banner "partitions not found" 40 "-"
	fi
}

erase() {
	echo "esptool.py -p $port -c $board -b $baudrate erase_flash"
	esptool.py -p $port -c $board -b $baudrate erase_flash
}

flash_upload() {
	if [[ $(/usr/bin/ls $port 2>/dev/null) == "" ]]; then
		generate_banner "port $port does not exist!" 80 "-"
		exit 1
	fi
	echo "arduino-cli upload --fqbn $board_fqbn --input-dir $bin_folder --port $port"
	arduino-cli upload --fqbn $board_fqbn --input-dir $bin_folder --port $port
}

flash_ota() {
	if [[ $flash_fs == true && $flash_fw == true ]]; then
		generate_banner "pushing firmware + FS OTA" 40 "+"
		if [[ ! -z "$auth" ]]; then
			echo "espota.py -i $ip -p $net_port -a $auth -f \"$bin_folder/$firmware_file\""
			espota.py -i $ip -p $net_port -a $auth -f "$bin_folder/$firmware_file"
			echo "waiting 15s for the esp to connect to network"
			sleep 15
			echo "espota.py -i $ip -p $net_port -a $auth -s -f \"$bin_folder/$filesystem_file\""
			espota.py -i $ip -p $net_port -a $auth -s -f "$bin_folder/$filesystem_file"
		elif [[ -z "$auth" ]]; then
			echo "espota.py -i $ip -p $net_port -f \"$bin_folder/$firmware_file\""
			espota.py -i $ip -p $net_port -f "$bin_folder/$firmware_file"
			echo "waiting 15s for the esp to connect to network"
			sleep 15
			echo "espota.py -i $ip -p $net_port -s -f \"$bin_folder/$filesystem_file\""
			espota.py -i $ip -p $net_port -s -f "$bin_folder/$filesystem_file"
		fi
	elif [[ $flash_fs == false && $flash_fw == true ]]; then
		generate_banner "pushing firmware OTA" 40 "+"
		if [[ ! -z "$auth" ]]; then
			echo "espota.py -i $ip -p $net_port -a $auth -f \"$bin_folder/$firmware_file\""
			espota.py -i $ip -p $net_port -a $auth -f "$bin_folder/$firmware_file"
		elif [[ -z "$auth" ]]; then
			echo "espota.py -i $ip -p $net_port -f \"$bin_folder/$firmware_file\""
			espota.py -i $ip -p $net_port -f "$bin_folder/$firmware_file"
		fi
	elif [[ $flash_fs == true && $flash_fw == false ]]; then
		generate_banner "pushing FS OTA" 40 "+"
		if [[ ! -z "$auth" ]]; then
			echo "espota.py -i $ip -p $net_port -a $auth -s -f \"$bin_folder/$filesystem_file\""
			espota.py -i $ip -p $net_port -a $auth -s -f "$bin_folder/$filesystem_file"
		elif [[ -z "$auth" ]]; then
			echo "espota.py -i $ip -p $net_port -s -f \"$bin_folder/$filesystem_file\""
			espota.py -i $ip -p $net_port -s -f "$bin_folder/$filesystem_file"
		fi
	fi
}

monitor() {
	echo "arduino-cli monitor -p $port -c baudrate=$serial"
	arduino-cli monitor -p $port -c baudrate=$serial
}

while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
		-c | --compile)
			# COMPILE
			generate_banner "COMPILING FIRMWARE" 80 "+"
			compile
			shift
			;;
		-f | --filesystem)
			# FILESYSTEM
			if [[ $flash_fs == true ]]; then
				generate_banner "FLASHING FILESYSTEM" 80 "+"
				if [[ $board == "esp8266" ]]; then
					flash_fs_esp8266					
				elif [[ $board == "esp32" ]]; then
					flash_fs_esp32
				fi
			else
				generate_banner "flash_fs not enabled!" 80 "-"
			fi
			shift
			;;
		-e | --erase)
			# ERASE
			if [[ $erase_flash == true ]]; then
				generate_banner "ERASING ENTIRE FLASH" 80 "+"
				erase
			else
				generate_banner "erase_flash not enabled!" 80 "-"
			fi
			shift
			;;
		-u | --upload)
			# UPLOAD
			if [[ $flash_fw == true ]]; then
				generate_banner "FLASHING FILESYSTEM" 80 "+"
				flash_upload
			else
				generate_banner "flash_fs not enabled!" 80 "-"
			fi
			shift
			;;
		-o | --upload-ota)
			# UPLOAD OTA
			if [[ $ota == true ]]; then
				generate_banner "FLASHING OTA" 80 "+"
				flash_ota
			else
				generate_banner "ota not enabled!" 80 "-"
			fi
			shift
			;;
		-r | --run)
			# RUN
			generate_banner "COMPILING FIRMWARE" 80 "+"
			compile
			if [[ $ota == true ]]; then
				generate_banner "FLASHING OTA" 80 "+"
				flash_ota
			else
				if [[ $erase_flash == true ]]; then
					generate_banner "" 80 "+"
					command
				fi
				if [[ $flash_fw == true ]]; then
					generate_banner "FLASHING FIRMWARE" 80 "+"
					flash_upload
				fi
				if [[ $flash_fs == true ]]; then
					generate_banner "FLASHING FILESYSTEM" 80 "+"
					if [[ $board == "esp8266" ]]; then
						flash_fs_esp8266					
					elif [[ $board == "esp32" ]]; then
						flash_fs_esp32
					fi
				fi
				generate_banner "MONITOR MODE" 80 "+"
				monitor
			fi

			shift
			;;
		-m | --monitor)
			# MONITOR
			monitor
			shift
			;;
		*)
			usage
			shift
			;;
	esac
done
