#!/usr/bin/zsh

config="$(pwd)/project.conf"

. $config

data_folder="data"
bin_folder="build/bin"
tmp_folder="build/tmp"
firmware_file="$bin_folder/${PWD##*/}.ino.bin"
filesystem_file="$bin_folder/filesystem.bin"

# Reset
NC='\033[0m'              # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White


usage() {
	echo "[-c <--compile>] [-f <--filesystem>] [-e <--erase>] [-u <--upload>] [-o <--upload-ota>] [-m <--monitor>]" 1>&2
	exit 1
}

if [[ -z $1 ]]; then
	usage
fi

check_vars() {
	# ota, ip, net_port, auth, baudrate, serial, port, total_memory
	# flash_fw, flash_fs, erase_flash, board, board_fqbn
	local err_msg="Check config file for missing variable"
	if [[ -z $ota ]]; then echo $err_msg; exit 1;fi
	if [[ -z $ip ]]; then echo $err_msg; exit 1;fi
	if [[ -z $net_port ]]; then echo $err_msg; exit 1;fi
	if [[ -z $auth ]]; then echo $err_msg; exit 1;fi
	if [[ -z $baudrate ]]; then echo $err_msg; exit 1;fi
	if [[ -z $serial ]]; then echo $err_msg; exit 1;fi
	if [[ -z $port ]]; then echo $err_msg; exit 1;fi
	if [[ -z $total_memory ]]; then echo $err_msg; exit 1;fi
	if [[ -z $flash_fw ]]; then echo $err_msg; exit 1;fi
	if [[ -z $flash_fs ]]; then echo $err_msg; exit 1;fi
	if [[ -z $erase_flash ]]; then echo $err_msg; exit 1;fi
	if [[ -z $board ]]; then echo $err_msg; exit 1;fi
	if [[ -z $board_fqbn ]]; then echo $err_msg; exit 1;fi
	unset err_msg
}

check_vars

baud() {
	generate_banner "invalid baudrate!" 80 "-"  "$BRed"
	echo -e "\nAvailable baudrates: 57600, 115200, 230400, 460800, 921600." 1>&2
	exit 1
}

speeds=(57600 115200 230400 460800 921600)
(($baudrate == 57600 || $baudrate == 115200 || $baudrate == 230400 || $baudrate == 460800 || $baudrate == 921600)) || baud

if [[ ! $ip =~ '\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}\b' ]]; then
	generate_banner "$ip is not a valid IP address!" 80 "-"  "$BRed"
	exit 1
fi

if [[ ! $net_port =~ '^[0-9]+$' ]]; then
	generate_banner "$net_port is not a valid port number!" 80 "-"  "$BRed"
	exit 1
fi

if [ ! -d $(pwd)/build ]; then
  mkdir build
fi
if [ ! -d $(pwd)/build/bin ]; then
  mkdir build/bin
fi
if [ ! -d $(pwd)/build/tmp ]; then
  mkdir build/tmp
fi

wait_online() {
	local e1=0
	echo "checking if target $ip is up"
	while ! fping -c1 -t500 "$ip">/dev/null 2>&1; do
		if [[ $e1 == 0 ]]; then
			echo "target is not up, waiting.."
			e1=1
		fi
		sleep 1
	done
	echo "target is up, resuming flow"
}

generate_banner() {
    local string="$1"
    local length="$2"
    local symbol="$3"
    local color="$4"
    local symbol_length=${#symbol}
    local text_length=${#string}
    local remaining_length=$((length - symbol_length * 2 - text_length))
    local half_remaining_length=$((remaining_length / 2))
    local banner=""
    for ((i=0; i<half_remaining_length; i++)); do
        banner+="$symbol"
    done
    if [[ $color == "" ]]; then
        color=$NC
    fi
    banner+=" $color$string$NC "
    for ((i=0; i<half_remaining_length; i++)); do
        banner+="$symbol"
    done
    local total_length=${#banner}
    local remaining_chars=$((length - total_length))
    for ((i=0; i<remaining_chars; i++)); do
        banner+="$symbol"
    done
    echo -e "$banner"
}

compile() {
	if [ -e "$tmp_folder/error.log" ]; then rm $tmp_folder/error.log;fi
	echo "arduino-cli compile --fqbn $board_fqbn --board-options $board_options --build-path $tmp_folder --output-dir $bin_folder 2>$tmp_folder/error.log"
	arduino-cli compile --fqbn $board_fqbn --board-options $board_options --build-path $tmp_folder --output-dir $bin_folder 2>$tmp_folder/error.log
	if [ -s $tmp_folder/error.log ]; then
		generate_banner "COMPILATION ERRORS FOUND" 80 "-" "$BRed"
		cat $tmp_folder/error.log
		generate_banner "ABORTING!" 80 "-" "$BRed"
		exit 1
	else
		if [ -e "$tmp_folder/error.log" ]; then rm $tmp_folder/error.log;fi
		generate_banner "COMPILATION SUCCESSFUL" 80 "+" "$BGreen"
	fi
}

flash_fs_esp8266() {
	if [[ $fs_size == "1M" ]];then
		fs_size=1024000
	elif [[ $fs_size == "2M" ]];then
		fs_size=2072576
	elif [[ $fs_size == "3M" ]];then
		fs_size=3121152
	else
		generate_banner "fs_size not specified!" 80 "-"  "$BRed"
		exit 1
	fi
	fs_address="0x$(echo "4-${fs_size::1}"|bc)00000"
	mklittlefs -c $data_folder -p 256 -b 8192 -s $fs_size "$filesystem_file"
	generate_banner "$board:$fs_address:$fs_size" 40 "+" "BYellow"
	echo "esptool.py -p $port -c $board -b $baudrate write_flash $fs_address \"$filesystem_file\""
	esptool.py -p $port -c $board -b $baudrate write_flash $fs_address "$filesystem_file"
}

flash_fs_esp32() {
	if test -f "$tmp_folder/partitions.csv"; then
		generate_banner "found partitions" 40 "+" "BGreen"
		fs_size=$(cat $tmp_folder/partitions.csv|rg spiffs|awk -F ',' '{print $5}')
		fs_address=$(cat $tmp_folder/partitions.csv|rg spiffs|awk -F ',' '{print $4}'|sed 's/\s*//g')
		mkspiffs -c $data_folder -s $fs_size "$filesystem_file"
		generate_banner "$board:$fs_address:$fs_size" 40 "+" "BYellow"
		echo "esptool.py -p $port -c $board -b $baudrate write_flash $fs_address \"$filesystem_file\""
		esptool.py -p $port -c $board -b $baudrate write_flash $fs_address "$filesystem_file"
	else
		generate_banner "partitions not found" 40 "-"  "$BRed"
	fi
}

erase() {
	echo "esptool.py -p $port -c $board -b $baudrate erase_flash"
	esptool.py -p $port -c $board -b $baudrate erase_flash
}

flash_upload() {
	if [[ $(/usr/bin/ls $port 2>/dev/null) == "" ]]; then
		generate_banner "port $port does not exist!" 80 "-"  "$BRed"
		exit 1
	fi
	echo "arduino-cli upload --fqbn $board_fqbn --input-dir $bin_folder --port $port"
	arduino-cli upload --fqbn $board_fqbn --input-dir $bin_folder --port $port
}

flash_ota() {
	if [[ $flash_fs == true && $flash_fw == true ]]; then
		generate_banner "pushing firmware + FS OTA" 40 "+" "$BGreen"
		if [[ ! -z "$auth" ]]; then
			wait_online
			echo "espota.py -i $ip -p $net_port -a $auth -f \"$firmware_file\""
			espota.py -i $ip -p $net_port -a $auth -f "$firmware_file"
			echo "waiting 15s for the esp to connect to network"
			sleep 15
			wait_online
			echo "espota.py -i $ip -p $net_port -a $auth -s -f \"$filesystem_file\""
			espota.py -i $ip -p $net_port -a $auth -s -f "$filesystem_file"
		elif [[ -z "$auth" ]]; then
			wait_online
			echo "espota.py -i $ip -p $net_port -f \"$firmware_file\""
			espota.py -i $ip -p $net_port -f "$firmware_file"
			echo "waiting 15s for the esp to connect to network"
			sleep 15
			wait_online
			echo "espota.py -i $ip -p $net_port -s -f \"$filesystem_file\""
			espota.py -i $ip -p $net_port -s -f "$filesystem_file"
		fi
	elif [[ $flash_fs == false && $flash_fw == true ]]; then
		generate_banner "pushing firmware OTA" 40 "+" "$BGreen"
		if [[ ! -z "$auth" ]]; then
			wait_online
			echo "espota.py -i $ip -p $net_port -a $auth -f \"$firmware_file\""
			espota.py -i $ip -p $net_port -a $auth -f "$firmware_file"
		elif [[ -z "$auth" ]]; then
			wait_online
			echo "espota.py -i $ip -p $net_port -f \"$firmware_file\""
			espota.py -i $ip -p $net_port -f "$firmware_file"
		fi
	elif [[ $flash_fs == true && $flash_fw == false ]]; then
		generate_banner "pushing FS OTA" 40 "+" "$BGreen"
		if [[ ! -z "$auth" ]]; then
			wait_online
			echo "espota.py -i $ip -p $net_port -a $auth -s -f \"$filesystem_file\""
			espota.py -i $ip -p $net_port -a $auth -s -f "$filesystem_file"
		elif [[ -z "$auth" ]]; then
			wait_online
			echo "espota.py -i $ip -p $net_port -s -f \"$filesystem_file\""
			espota.py -i $ip -p $net_port -s -f "$filesystem_file"
		fi
	fi
}

monitor() {
	echo "arduino-cli monitor -p $port -c baudrate=$serial"
	arduino-cli monitor -p $port -c baudrate=$serial
}

while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
		-c | --compile)
			# COMPILE
			generate_banner "COMPILING FIRMWARE" 80 "+" "$BYellow"
			compile
			shift
			;;
		-f | --filesystem)
			# FILESYSTEM
			generate_banner "FLASHING FILESYSTEM" 80 "+" "$BYellow"
			if [[ $board == "esp8266" ]]; then
				flash_fs_esp8266					
			elif [[ $board == "esp32" ]]; then
				flash_fs_esp32
			fi
			shift
			;;
		-e | --erase)
			# ERASE
			generate_banner "ERASING ENTIRE FLASH" 80 "+" "$BYellow"
			erase
			shift
			;;
		-u | --upload)
			# UPLOAD
			generate_banner "FLASHING FIRMWARE" 80 "+" "$BYellow"
			flash_upload
			shift
			;;
		-o | --upload-ota)
			# UPLOAD OTA
			generate_banner "FLASHING OTA" 80 "+" "$BYellow"
			flash_ota
			shift
			;;
		-r | --run)
			# RUN
			generate_banner "COMPILING FIRMWARE" 80 "+" "$BYellow"
			compile
			if [[ $ota == true ]]; then
				generate_banner "FLASHING OTA" 80 "+" "$BYellow"
				flash_ota
			else
				if [[ $erase_flash == true ]]; then
					generate_banner "" 80 "+" "$BYellow"
					command
				fi
				if [[ $flash_fw == true ]]; then
					generate_banner "FLASHING FIRMWARE" 80 "+" "$BYellow"
					flash_upload
				fi
				if [[ $flash_fs == true ]]; then
					generate_banner "FLASHING FILESYSTEM" 80 "+" "$BYellow"
					if [[ $board == "esp8266" ]]; then
						flash_fs_esp8266					
					elif [[ $board == "esp32" ]]; then
						flash_fs_esp32
					fi
				fi
			fi

			shift
			;;
		-m | --monitor)
			# MONITOR
			generate_banner "MONITOR MODE" 80 "+" "$BGreen"
			monitor
			shift
			;;
		*)
			usage
			shift
			;;
	esac
done

generate_banner "DONE" 80 "+" "$BGreen"