#!/usr/bin/zsh

config="$(pwd)/project.conf"

. $config

folder="build/$(echo $board_fqbn|sed 's/:/./g')"




# COMPILE
echo "arduino-cli compile --fqbn $board_fqbn --board-options $board_options -e ."
arduino-cli compile --fqbn $board_fqbn --board-options $board_options -e .
# ERASE
# echo "esptool.py -p $port -c $board -b $baudrate erase_flash"
# esptool.py -p $port -c $board -b $baudrate erase_flash
# UPLOAD
# echo "arduino-cli upload --fqbn $board_fqbn --input-dir $folder --port $port"
# arduino-cli upload --fqbn $board_fqbn --input-dir $folder --port $port
# MONITOR
# echo "arduino-cli monitor -p $port -c baudrate=$baudrate"
# arduino-cli monitor -p $port -c baudrate=$baudrate
