#!/usr/bin/zsh

ota=false
ip="192.168.0.170"
net_port=600
auth=""
baudrate="460800"
port="/dev/ttyUSB0"
fs_size="1M"
flash_fw=true
flash_fs=false
erase_flash=false

baud() {
	echo -e "Invalid baudrate.\nAvailable baudrates: 57600, 115200, 230400, 460800, 921600." 1>&2
	exit 1
}
port() {
	out="$(ls /dev | rg ttyUSB)"
	if [ -z "$out" ]; then
		echo "Invalid port. Port should look like '/dev/ttyUSB0'" 1>&2
	else
		echo -e "Invalid port. Port should be one of:\n$(echo $out | sed 's/ /\n/g' | sed 's/^/\/dev\//g')" 1>&2
	fi
	exit 1
}
usage() {
	echo "Usage: $0 [-b <baudrate>] [-p <port>] [-fw <true|false>] [-fs <true|false>] [-e <true|false>]" 1>&2
	exit 1
}

while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
	-b | --baud)
		if [[ ! -z "$2" && $2 != -* ]]; then
			baudrate="$2"
			shift
		fi
		speeds=(57600 115200 230400 460800 921600)
		(($baudrate == 57600 || $baudrate == 115200 || $baudrate == 230400 || $baudrate == 460800 || $baudrate == 921600)) || baud
		shift
		;;
	-p | --port)
		if [[ ! -z "$2" && $2 != -* ]]; then
			port="$2"
			shift
		fi
		shift
		;;
	-fw | --firmware)
		if [[ $2 == "true" || $2 == "false" ]]; then
			flash_fw=$2
			shift
		fi
		shift
		;;
	-fs | --filesystem)
		if [[ $2 == "true" || $2 == "false" ]]; then
			flash_fs=$2
			shift
		fi
		shift
		;;
	-o | --ota)
		if [[ $2 == "true" || $2 == "false" ]]; then
			ota=$2
			shift
		fi
		shift
		;;
	-ip)
		if [[ ! -z "$2" && $2 != -* ]]; then
			ip="$2"
			shift
		fi
		if [[ ! $ip =~ '\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}\b' ]]; then
			echo "$ip is not a valid IP address."
			exit 1
		fi
		shift
		;;
	-np)
		if [[ ! -z "$2" && $2 != -* ]]; then
			net_port="$2"
			shift
		fi
		if [[ ! $net_port =~ '^[0-9]+$' ]]; then
			echo "$net_port is not a valid port number."
			exit 1
		fi
		shift
		;;
	-a | --auth)
		if [[ ! -z "$2" && $2 != -* ]]; then
			auth="$2"
			shift
		fi
		shift
		;;
	-e | --erase)
		if [[ $2 == "true" || $2 == "false" ]]; then
			erase_flash=$2
			shift
		fi
		shift
		;;
	*)
		# usage
		shift
		;;
	esac
done

if [[ $(/usr/bin/ls $port 2>/dev/null) == "" ]] && [[ $ota == false ]]; then
	echo "Port $port does not exist."
	exit 1
fi

tmp=$(du -h build/fs.bin | sed 's/1000K/1.0M/g' | rg -o -e "\d\.\d\w" | sed 's/\.0//g')
if [[ $tmp == "1M" || $tmp == "2M" || $tmp == "3M" ]]; then
	fs_size=$tmp
	unset tmp
else
	echo "FS file corrupt, aborting."
	exit 1
fi

echo -e "\n===================="
echo OTA: $ota
if [[ $ota == true ]]; then
	echo IP: $ip
	echo port: $net_port
	echo auth: $auth
elif [[ $ota == false ]]; then
	echo port: $port
	echo baudrate: $baudrate
fi
echo fs_size: $fs_size
echo flash_firmware: $flash_fw
echo flash_fs: $flash_fs
echo erase_flash: $erase_flash
echo -e "====================\n"

if [[ $erase_flash == true ]] && [[ $ota == false ]]; then
	echo "erasing flash"
	esptool.py -p $port -c esp32 -b $baudrate erase_flash
elif [[ $erase_flash == true ]] && [[ $ota == true ]]; then
	echo "cannot erase flash OTA"
	exit 1
fi

if [[ $flash_fs == true && $flash_fw == true ]]; then
	if [[ $ota == true ]]; then
		echo "pushing firmware + FS OTA"
		if [[ ! -z "$auth" ]]; then
			echo "espota.py -i $ip -p $net_port -a $auth -f build/firmware.bin"
			espota.py -i $ip -p $net_port -a $auth -f build/firmware.bin
			echo "waiting 15s for the esp to connect to network"
			sleep 15
			echo "espota.py -i $ip -p $net_port -a $auth -s -f build/fs.bin"
			espota.py -i $ip -p $net_port -a $auth -s -f build/fs.bin
		elif [[ -z "$auth" ]]; then
			echo "espota.py -i $ip -p $net_port -f build/firmware.bin"
			espota.py -i $ip -p $net_port -f build/firmware.bin
			echo "waiting 15s for the esp to connect to network"
			sleep 15
			echo "espota.py -i $ip -p $net_port -s -f build/fs.bin"
			espota.py -i $ip -p $net_port -s -f build/fs.bin
		fi
	elif [[ $ota == false ]]; then
		echo "flashing firmware + FS"
		if [[ $fs_size == "1M" ]]; then
			echo "esptool.py -p $port -c esp32 -b $baudrate write_flash 0x0 build/firmware.bin 0x300000 build/fs.bin"
			esptool.py -p $port -c esp32 -b $baudrate write_flash 0x0 build/firmware.bin 0x300000 build/fs.bin
		elif [[ $fs_size == "2M" ]]; then
			echo "esptool.py -p $port -c esp32 -b $baudrate write_flash 0x0 build/firmware.bin 0x200000 build/fs.bin"
			esptool.py -p $port -c esp32 -b $baudrate write_flash 0x0 build/firmware.bin 0x200000 build/fs.bin
		elif [[ $fs_size == "3M" ]]; then
			echo "esptool.py -p $port -c esp32 -b $baudrate write_flash 0x0 build/firmware.bin 0x100000 build/fs.bin"
			esptool.py -p $port -c esp32 -b $baudrate write_flash 0x0 build/firmware.bin 0x100000 build/fs.bin
		fi
	fi
elif [[ $flash_fs == false && $flash_fw == true ]]; then
	if [[ $ota == true ]]; then
		if [[ ! -z "$auth" ]]; then
			echo "pushing firmware OTA"
			echo "espota.py -i $ip -p $net_port -a $auth -f build/firmware.bin"
			espota.py -i $ip -p $net_port -a $auth -f build/firmware.bin
		elif [[ -z "$auth" ]]; then
			echo "pushing firmware OTA"
			echo "espota.py -i $ip -p $net_port -f build/firmware.bin"
			espota.py -i $ip -p $net_port -f build/firmware.bin
		fi
	elif [[ $ota == false ]]; then
		echo "flashing firmware only"
		echo "esptool.py -p $port -c esp32 -b $baudrate write_flash 0x0 build/firmware.bin"
		esptool.py -p $port -c esp32 -b $baudrate write_flash 0x0 build/firmware.bin
	fi
elif [[ $flash_fs == true && $flash_fw == false ]]; then
	if [[ $ota == true ]]; then
		if [[ ! -z "$auth" ]]; then
			echo "pushing FS OTA"
			echo "espota.py -i $ip -p $net_port -a $auth -s -f build/fs.bin"
			espota.py -i $ip -p $net_port -a $auth -s -f build/fs.bin
		elif [[ -z "$auth" ]]; then
			echo "pushing FS OTA"
			echo "espota.py -i $ip -p $net_port -s -f build/fs.bin"
			espota.py -i $ip -p $net_port -s -f build/fs.bin
		fi
	elif [[ $ota == false ]]; then
		echo "flashing FS only"
		if [[ $fs_size == "1M" ]]; then
			echo "esptool.py -p $port -c esp32 -b $baudrate write_flash 0x300000 build/fs.bin"
			esptool.py -p $port -c esp32 -b $baudrate write_flash 0x300000 build/fs.bin
		elif [[ $fs_size == "2M" ]]; then
			echo "esptool.py -p $port -c esp32 -b $baudrate write_flash 0x200000 build/fs.bin"
			esptool.py -p $port -c esp32 -b $baudrate write_flash 0x200000 build/fs.bin
		elif [[ $fs_size == "3M" ]]; then
			echo "esptool.py -p $port -c esp32 -b $baudrate write_flash 0x100000 build/fs.bin"
			esptool.py -p $port -c esp32 -b $baudrate write_flash 0x100000 build/fs.bin
		fi
	fi
fi
